baseURL = "https://mean-machine-gc.github.io/ubi-framework/"
languageCode = "en"
title = "Ubi."
enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "A fundamental model for complex information processing systems"
  author = "Giovanni Chiodi"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokailight"
    lineNos = false
    noClasses = false

[menu]
  [[menu.main]]
    name = "Blueprint"
    url = "/blueprint/summary/"
    weight = 1
  [[menu.main]]
    name = "SDLC"
    url = "/sdlc/summary/"
    weight = 2
  [[menu.main]]
    name = "Toolkit"
    url = "/toolkit/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
